# A string used to distinguish different Supabase projects on the same machine.
# Not required if you have a single project.
project_id = "kakomonn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "http://localhost:3000"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation_enabled = true

[edge_runtime]
enabled = true
port = 54328

[analytics]
enabled = false
port = 54329
vector_port = 54330
gw_port = 54331